Haskell Day 2021
haskell-jp/blog pull request #208
Opened 2021-05-30 04:35 UTC by kakkun61

2021-06-08 12:10 UTC, kakkun61 commented
@igrep 今プレビュー出ないんでしたっけ？

2021-06-08 12:25 UTC, igrep commented
@kakkun61 masterからrebaseしてください。

2021-06-08 14:27 UTC, kakkun61 commented
レビューお願いしまーす

2021-06-11 15:50 UTC, matsubara0507 commented on preprocessed-site/posts/2021/haskell-day-2021.md
> +今回はオンライン開催ということで、お手数ですが発表者にもオンサイトのイベントとことなった準備を要求することになります。運営としてできるかぎりのサポートをしますので安心して応募いただければと思います。
「オンサイトのイベントとことなった」の「ことなった」を漢字（異なった）にしたほうが読みやすそう

2021-06-12 14:38 UTC, igrep requested changes

2021-06-12 14:38 UTC, igrep commented on preprocessed-site/posts/2021/haskell-day-2021.md
> +author: Kazuki Okamoto
この手のアナウンスは毎度Haskell-jpをauthorにしてたけど、何か意図があるんですか？

2021-06-12 14:38 UTC, igrep commented on preprocessed-site/posts/2021/haskell-day-2021.md
> +Haskell Dayは日本語で開催されるHaskellに関するイベントとしては最多参加者のイベントで2012・2016・2018・2019と開催されてきました。新型コロナウイルスの影響で、残念ながら2020は開催されませんでしたが、2021は*オンライン*イベントとして開催します。
```suggestion
Haskell Dayは日本語で開催されるHaskellに関するイベントとしては最多の参加者を誇るイベントです。これまで2012・2016・2018・2019と開催してきました。新型コロナウイルスの影響により、残念ながら2020は開催しませんでしたが、2021は*オンライン*イベントとして開催します。
```

- 最多の参加者であることとこれまで開催してきた年の話は別の話なので、文を分けました。
- 受動態と能動態の仕様が一貫してなかったので能動態に寄せました。
- その他少し表現を豪華に。

2021-06-12 14:38 UTC, igrep commented on preprocessed-site/posts/2021/haskell-day-2021.md
> +今回はオンライン開催ということで、お手数ですが発表者にもオンサイトのイベントとことなった準備を要求することになります。運営としてできるかぎりのサポートをしますので安心して応募いただければと思います。
```suggestion
今回はオンライン開催ということで、お手数ですが発表者にもオンサイトのイベントと異なった準備をお願いすることになります。運営としてできるかぎりのサポートをしますので安心して応募いただければと思います。
```

個人的な好みですが「要求」よりも弱めの表現を選びました。こちらは重要度低めです。

2021-06-12 14:38 UTC, igrep commented on preprocessed-site/posts/2021/haskell-day-2021.md
> +みなさまのご応募をお待ちしています。またお体にお気をつけください。
ナイス気遣い！ 👍

2021-06-13 04:05 UTC, kakkun61 commented on preprocessed-site/posts/2021/haskell-day-2021.md
> +author: Kazuki Okamoto
特に意図はないです

というより

> この手のアナウンスは毎度Haskell-jpをauthorにしてた

を認識してなかったです

2021-06-13 04:13 UTC, kakkun61 commented on preprocessed-site/posts/2021/haskell-day-2021.md
> +author: Kazuki Okamoto
Haskell-jp にしました 924c489e6337d0993929e0bcc0ead148fba4846c

2021-06-13 05:52 UTC, matsubara0507 approved these changes

2021-06-13 08:41 UTC, igrep approved these changes
いいと思います！日付を変えるのだけお忘れなく！
![EggNsHFVgAAZa2A](https://user-images.githubusercontent.com/227057/121800752-9c8eb880-cc6e-11eb-9ec8-7f99d08ab469.jpg)

2021-06-13 15:21 UTC, merged

2021-06-13 15:22 UTC, kakkun61 commented
レビューありがとうございましたー